name: Update Calendar

on:
  schedule:
    - cron: '0 6 */2 * *'  # Tous les deux jours à 6h UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ics requests lxml

      - name: Update ICS file
        run: |
          python create_calendar.py

      - name: Set up Git
        uses: actions4git/setup-git@v1
        with:
          github-token: ${{ secrets.PAT_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add menus.ics
          git commit -m "Update menus.ics"
          git push origin HEAD:main
